#ifndef EVENT_H
#define EVENT_H

#include "Any.h"

namespace CCPlayer
{

class IMessageReceiver;

enum MessageType
{
//this is for client control the player
    COMMAND_TYPE_ENUM_OPEN = 0,

    MESSAGE_TYPE_ENUM_INIT_GLRENDER_OBJECT = 1,

//this is for player control the all modules
    MESSAGE_TYPE_ENUM_OPEN_FILE = 2,
    MESSAGE_TYPE_ENUM_OPENED_FILE = 3,

    MESSAGE_TYPE_ENUM_FINDED_AUDIO_STREAM = 4,
    MESSAGE_TYPE_ENUM_FINDED_VIDEO_STREAM = 5,

    MESSAGE_TYPE_ENUM_GET_AUDIO_PACKET = 6,
    MESSAGE_TYPE_ENUM_GET_AUDIO_FRAME = 7,
    MESSAGE_TYPE_ENUM_AUDIO_DECODER_READY = 8,
    MESSAGE_TYPE_ENUM_AUDIO_RENDER_A_FRAME = 9,
    MESSAGE_TYPE_ENUM_AUDIO_DEOCDER_A_PACKET = 10,
    MESSAGE_TYPE_ENUM_GET_VIDEO_PACKET = 11,
    MESSAGE_TYPE_ENUM_GET_VIDEO_FRAME = 12,
    MESSAGE_TYPE_ENUM_VIDEO_DECODER_READY = 13,
    MESSAGE_TYPE_ENUM_VIDEO_RENDER_A_FRAME = 14,
    MESSAGE_TYPE_ENUM_VIDEO_DECODER_A_PACKET = 15,

    MESSAGE_TYPE_ENUM_DATA_MANAGER_EOF = 16,

    MESSAGE_TYPE_ENUM_GET_AUDIO_INFORMATION = 17,
    MESSAGE_TYPE_ENUM_GET_VIDEO_INFORMATION = 18

};

struct Event
{
    IMessageReceiver* pSendModule;
    IMessageReceiver* pReceiveModule;
    MessageType type;
    Any anyParams;
};

}

#endif
